onboarding = false

[keys]
prefix = "alt+q"
# Misc
settings = "prefix+S"
edit_scrollback = "prefix+["
copy_mode = "prefix+]"
reload_config = "prefix+alt+r"
# Tab and panes
new_tab = "prefix+n"
next_tab = "prefix+L"
previous_tab = "prefix+H"
move_tab_previous = "alt+shift+left"
move_tab_next = "alt+shift+right"
focus_pane_left = "prefix+h"
focus_pane_right = "prefix+l"
focus_pane_down = "prefix+j"
focus_pane_up = "prefix+k"
split_horizontal = "prefix+s"
split_vertical = "prefix+v"
rename_tab = "prefix+r"
rename_pane = "prefix+R"
resize_mode = "prefix+z"
resize_pane_left = "alt+Left"
resize_pane_right = "alt+Right"
resize_pane_down = "alt+Down"
resize_pane_up = "alt+Up"
close_pane = "prefix+c"
close_tab = "prefix+shift+c"
zoom = "prefix+f"
goto = "prefix+\\"
# Workspace
close_workspace = "prefix+x"
previous_workspace = "prefix+shift+k"
next_workspace = "prefix+shift+j"
switch_workspace = "prefix+shift+1..9"
# Navigate mode (prefix+w). Workspaces vertical, panes horizontal.
navigate_workspace_down = "j"
navigate_workspace_up = "k"

[ui]
prompt_new_tab_name = false
status_indicators = "symbols"        # symbols | dots
tab_bar_position = "top"             # top | bottom
hide_tab_bar_when_single_tab = false
confirm_close = true
sidebar_collapsed_mode = "compact"   # compact | hidden

[ui.sound]
enabled = false

[ui.toast]
delivery = "herdr"

[ui.toast.herdr]
position = "top-right"

[terminal]
new_cwd = "home"

[theme]
name = "catppuccin"
auto_switch = false

[[keys.command]]
key = "prefix+d"
type = "shell"
command = "\"$HERDR_BIN_PATH\" tab create --cwd \"$HERDR_ACTIVE_PANE_CWD\" --focus"
description = "duplicate tab in current cwd"

[[keys.command]]
key = "prefix+e"
type = "popup"
command = "/home/linuxbrew/.linuxbrew/bin/fish -c yazi"
description = "yazi file manager"
width = "90%"
height = "90%"

[[keys.command]]
key = "prefix+/"
type = "popup"
command = "/home/linuxbrew/.linuxbrew/bin/fish -c btop"
description = "Btop"
width = "90%"
height = "90%"
