font_family CaskaydiaCove Nerd Font
font_size 12.0

shell {{shell}}

cursor_shape block
cursor_blink_interval 0.5

window_padding_width 3
hide_window_decorations yes
background_opacity 1

scrollbar scrolled

tab_bar_edge bottom
tab_bar_style powerline

foreground #cad3f5
background #24273a
cursor #cad3f5
cursor_text_color #24273a

color0 #494d64
color1 #ed8796
color2 #a6da95
color3 #eed49f
color4 #8aadf4
color5 #f5bde6
color6 #8bd5ca
color7 #b8c0e0
color8 #5b6078
color9 #ed8796
color10 #a6da95
color11 #eed49f
color12 #8aadf4
color13 #f5bde6
color14 #8bd5ca
color15 #a5adcb

map_timeout 1.5
# map alt+q>n new_tab
# map alt+q>d new_tab_with_cwd
# map alt+q>c close_window_with_confirmation
# map alt+q>x close_tab
# map alt+q>f toggle_layout stack
# map alt+q>shift+l new_window horizontal
# map alt+q>shift+j new_window
# map alt+q>h neighboring_window left
# map alt+q>j neighboring_window down
# map alt+q>k neighboring_window up
# map alt+q>l neighboring_window right
# map alt+shift+h previous_tab
# map alt+shift+l next_tab
