vim.g.mapleader = " "
vim.g.maplocalleader = "\\"
vim.o.number = true
vim.o.relativenumber = true
vim.o.mouse = "a"
vim.o.showmode = false
vim.o.switchbuf = "usetab"
vim.o.clipboard = "unnamedplus"
vim.o.shell = "pwsh"
vim.o.smartcase = true
vim.o.smartindent = true
vim.o.ignorecase = true
vim.o.breakindent = false
vim.o.inccommand = "nosplit"
vim.o.foldlevel = 99 -- Necessary
vim.o.foldlevelstart = 99
vim.o.splitright = true
vim.o.splitbelow = true
vim.o.cmdheight = 1
vim.o.laststatus = 2
vim.o.signcolumn = "yes"
vim.o.wrap = false
vim.o.tabstop = 2
vim.o.shiftwidth = 2
vim.o.cursorline = true
vim.o.confirm = true
vim.o.formatoptions = "jcroqlnt" -- tcqj
vim.o.grepformat = "%f:%l:%c:%m"
vim.o.grepprg = "rg --vimgrep"
vim.o.scrolloff = 3
