---
gui:
  nerdFontsVersion: "3"
  showRandomTip: false
  showBranchCommitHash: false
  showCommandLog: true
  spinner:
    frames: ["⠋", "⠙", "⠹", "⠸", "⠼", "⠴", "⠦", "⠧", "⠇", "⠏"]
    rate: 120
git:
  fetchAll: true
  autoFetch: true
  mainBranches:
    - main
    - master
  pagers:
    - externalDiffCommand: difft --color=always --display=inline
services:
  "github.com": "gh pr create --fill --web"
customCommands:
  - key: o
    context: localBranches
    description: "Create PR with gh"
    command: gh pr create --fill --web
refresher:
  refreshInterval: 10
  fetchInterval: 30
