[helpers]

[default]
depends = []
[default.files]
bat = "~/.config/bat"
fastfetch = "~/.config/fastfetch"
btop = "~/.config/btop"
gh = "~/.config/gh"
lazygit = "~/.config/lazygit"
mise = "~/.config/mise"
nvim = "~/.config/nvim"
"opencode/opencode.json" = "~/.config/opencode/opencode.json"
rg = "~/.config/rg"
wezterm = "~/.config/wezterm"
yazi = "~/.config/yazi"
vimrc = "~/.vimrc"
"andrew.omp.json" = { target = "~/andrew.omp.json", type = "symbolic" }
gitconfig = "~/.gitconfig"
fish = "~/.config/fish"

[windows.files]
"windows-terminal/settings.json" = "~/AppData/Local/Packages/Microsoft.WindowsTerminal_8wekyb3d8bbwe/LocalState/settings.json"
Powershell = "~/Documents/PowerShell/"
"Powershell/Scripts" = "~/Documents/PowerShell/Scripts/"
"scoop-bak.json" = "~/scoop-bak.json"
"winget-apps.bak" = "~/winget-apps.bak"
".claude/settings.json" = "~/.claude/settings.json"
".claude/statusline-command.ps1" = "~/.claude/statusline-command.ps1"
[windows.variables]
shell = "pwsh"

[linux.files]
[linux.variables]
shell = "fish"

[default.variables]
username = "andrew nguyen"
email = "ngphuchoanganh@gmail.com"

[settings]
default_target_type = "automatic"
