[helpers]

[default]
depends = []
[default.files]
bat = "~/.config/bat"
fastfetch = "~/.config/fastfetch"
flameshot = "~/.config/flameshot"
btop = "~/.config/btop"
gh = "~/.config/gh"
herdr = "~/.config/herdr"
lazygit = "~/.config/lazygit"
mise = "~/.config/mise"
nvim = "~/.config/nvim"
"opencode/opencode.json" = "~/.config/opencode/opencode.json"
"mimocode/mimocode.jsonc" = "~/.config/mimocode/mimocode.jsonc"
rg = "~/.config/rg"
wezterm = "~/.config/wezterm"
yazi = "~/.config/yazi"
vimrc = "~/.vimrc"
"andrew.omp.json" = { target = "~/andrew.omp.json", type = "symbolic" }
"claude.omp.json" = { target = "~/claude.omp.json", type = "symbolic" }
".commandcode/settings.json" = "~/.commandcode/settings.json"
".commandcode/mcp.json" = "~/.commandcode/mcp.json"
".commandcode/hooks" = "~/.commandcode/hooks"
".commandcode/taste" = "~/.commandcode/taste"
gitconfig = "~/.gitconfig"
fish = "~/.config/fish"

[windows.files]
"windows-terminal/settings.json" = "~/AppData/Local/Packages/Microsoft.WindowsTerminal_8wekyb3d8bbwe/LocalState/settings.json"
Powershell = "~/Documents/PowerShell/"
"Powershell/Scripts" = "~/Documents/PowerShell/Scripts/"
"scoop-bak.json" = "~/scoop-bak.json"
"winget-apps.bak" = "~/winget-apps.bak"
[windows.variables]
shell = "pwsh"
disk = 'C:\\'

[linux.files]
kitty = "~/.config/kitty"
"opencode/cli.json" = "~/.config/opencode/cli.json"
[linux.variables]
shell = "/home/linuxbrew/.linuxbrew/bin/fish"
disk = "/"

[default.variables]
username = "andrew nguyen"
email = "ngphuchoanganh@gmail.com"

[settings]
default_target_type = "automatic"
